// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.GestionDeCommandeContext;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210528134352_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Domain.Models.Client", b =>
                {
                    b.Property<int>("CltId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Adresse")
                        .HasColumnType("text");

                    b.Property<string>("CodeClt")
                        .HasColumnType("text");

                    b.Property<string>("RaisonSocial")
                        .HasColumnType("text");

                    b.Property<string>("Tel")
                        .HasColumnType("text");

                    b.HasKey("CltId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Domain.Models.CommandeEntete", b =>
                {
                    b.Property<int>("IdCmdEnt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("ClientCltId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCmd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdClt")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontantTot")
                        .HasColumnType("numeric");

                    b.Property<string>("NumeroCmd")
                        .HasColumnType("text");

                    b.HasKey("IdCmdEnt");

                    b.HasIndex("ClientCltId");

                    b.ToTable("CommandeEntetes");
                });

            modelBuilder.Entity("Domain.Models.CommandeLigne", b =>
                {
                    b.Property<int>("IdCmdLigne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CommandeEnteteIdCmdEnt")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateLigne")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdCmdEnt")
                        .HasColumnType("integer");

                    b.Property<int>("IdProd")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrixProd")
                        .HasColumnType("numeric");

                    b.Property<int?>("ProduitIdProd")
                        .HasColumnType("integer");

                    b.Property<decimal>("QteLigne")
                        .HasColumnType("numeric");

                    b.HasKey("IdCmdLigne");

                    b.HasIndex("CommandeEnteteIdCmdEnt");

                    b.HasIndex("ProduitIdProd");

                    b.ToTable("CommandeLignes");
                });

            modelBuilder.Entity("Domain.Models.Produit", b =>
                {
                    b.Property<int>("IdProd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CodeProd")
                        .HasColumnType("text");

                    b.Property<string>("DesignationProd")
                        .HasColumnType("text");

                    b.Property<decimal>("PrixProd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QuantiteProd")
                        .HasColumnType("numeric");

                    b.HasKey("IdProd");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("Domain.Models.CommandeEntete", b =>
                {
                    b.HasOne("Domain.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientCltId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Domain.Models.CommandeLigne", b =>
                {
                    b.HasOne("Domain.Models.CommandeEntete", "CommandeEntete")
                        .WithMany("CommandeLignes")
                        .HasForeignKey("CommandeEnteteIdCmdEnt");

                    b.HasOne("Domain.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitIdProd");

                    b.Navigation("CommandeEntete");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("Domain.Models.CommandeEntete", b =>
                {
                    b.Navigation("CommandeLignes");
                });
#pragma warning restore 612, 618
        }
    }
}
